### ISSUE TITLE
Too many positional arguments

### ISSUE THREAD

**Issue by eliateguhpramono** [fluttercommunity/flutter_google_places#85]
I have found error too many positional argument with kGoogleApiKey
Please help me

![image](https://user-images.githubusercontent.com/56675542/66994666-34d24400-f100-11e9-811b-ca53720643a8.png)

**Comment by driveweyus** [comment]
Please help same

**Comment by KevMorelli** [comment]
As you can see those parameters are inside braces, which mean that they are optional.
![image](https://user-images.githubusercontent.com/12283570/74088927-460dda80-4a7a-11ea-886e-c2e8c2461534.png)

You should use it as 
GoogleMapsPlaces _places = GoogleMapsPlaces(apiKey: kGoogleApiKey);
to refer to it. 

Also, be careful when publishing screenshots of your code because in this case anyone can see your API key
